services:
  orcaopta:
    build:
      context: ..
      dockerfile: docker/Dockerfile.core
    container_name: orcaopta

    environment:
      ORCAOPTA_MASTER_KEY: "${ORCAOPTA_MASTER_KEY:-}"
      ORCAOPTA_DB_KEY: "${ORCAOPTA_DB_KEY:-}"
      ORCAOPTA_ARTIFACT_KEY: "${ORCAOPTA_ARTIFACT_KEY:-}"
      ORCAOPTA_CLUSTER_KEY: "${ORCAOPTA_CLUSTER_KEY:-}"
      ORCAOPTA_REPLICATION_KEY: "${ORCAOPTA_REPLICATION_KEY:-}"
      ORCAOPTA_OTS_KEY: "${ORCAOPTA_OTS_KEY:-}"
      ORCAOPTA_VECTOR_KEY: "${ORCAOPTA_VECTOR_KEY:-}"

      ORCAOPTA_MODE: "dev"
      PYTHONUNBUFFERED: "1"

    volumes:
      - ../mlruns:/app/mlruns
      - ../data:/app/data
      - ../logs:/app/logs
      - ../src:/app/src

    restart: unless-stopped

    command: >
      python -m orcaopta
