FROM python:3.12-slim AS base

ENV DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------
# Install system dependencies
# ---------------------------------------------------------
RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    libssl-dev \
    libffi-dev \
    default-jdk \
    default-jre-headless \
    && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------
# Install Node.js (LTS)
# ---------------------------------------------------------
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

WORKDIR /app

# ---------------------------------------------------------
# Backend
# ---------------------------------------------------------
COPY src/orcaopta /app/orcaopta
COPY spark_config.json /app/spark_config.json
COPY requirenments/requirements-core.txt /app/requirements-core.txt
COPY orcaopta.yaml /app/orcaopta.yaml


RUN pip install -r /app/requirements-core.txt
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
RUN pip install python-openstackclient setuptools

# ---------------------------------------------------------
# Frontend (Next.js)
# ---------------------------------------------------------
COPY src/orcaopta/orcaopta-dashboard /app/orcaopta-dashboard

WORKDIR /app/orcaopta-dashboard
RUN npm install
RUN npm run build

# ---------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------
WORKDIR /app
ENV PYTHONPATH="/app"

COPY ../scripts/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 8000
EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
