"""add OTS tables

Revision ID: 3e8b29caa69d
Revises: 7438b4f73554
Create Date: 2026-09-01 10:03:04.762715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8b29caa69d'
down_revision: Union[str, Sequence[str], None] = '7438b4f73554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ots_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_index(op.f('ix_ots_artifacts_run_id'), 'ots_artifacts', ['run_id'], unique=False)
    op.create_table('ots_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ots_events_run_id'), 'ots_events', ['run_id'], unique=False)
    op.create_table('ots_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ots_metrics_run_id'), 'ots_metrics', ['run_id'], unique=False)
    op.create_table('ots_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.add_column('artifacts', sa.Column('hash', sa.String(), nullable=False))
    op.add_column('artifacts', sa.Column('size_bytes', sa.Integer(), nullable=False))
    op.add_column('artifacts', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('artifacts', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('replication_log', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replication_log', 'message')
    op.drop_column('artifacts', 'version')
    op.drop_column('artifacts', 'meta')
    op.drop_column('artifacts', 'size_bytes')
    op.drop_column('artifacts', 'hash')
    op.drop_table('ots_runs')
    op.drop_index(op.f('ix_ots_metrics_run_id'), table_name='ots_metrics')
    op.drop_table('ots_metrics')
    op.drop_index(op.f('ix_ots_events_run_id'), table_name='ots_events')
    op.drop_table('ots_events')
    op.drop_index(op.f('ix_ots_artifacts_run_id'), table_name='ots_artifacts')
    op.drop_table('ots_artifacts')
    # ### end Alembic commands ###
